"""
Whitelisted macro substitution engine (tracking spec §4/§19).

Rules enforced here, always:
1. Only macros in APPROVED_MACROS are ever substituted — unknown `{...}`
   tokens pass through untouched (they may belong to the destination
   platform's own macro syntax).
2. Macros are string substitutions, never expressions — nothing is
   evaluated, so nothing can execute.
3. Every substituted value is URL-encoded and length-capped.
4. Empty/missing values substitute as empty strings, safely.
"""
import re
from urllib.parse import quote

MAX_MACRO_VALUE_LENGTH = 200

APPROVED_MACROS: frozenset[str] = frozenset(
    {
        "click_id", "quantix_click_id", "conversion_id", "transaction_id",
        "external_click_id", "agency_click_id", "external_conversion_id",
        "publisher_id", "publisher_code", "campaign_id", "campaign_code",
        "event", "goal", "status", "payout", "revenue", "currency",
        "date_time", "postback_received_at", "event_occurred_at",
        "ip", "country", "country_code", "state", "city",
        "campaign_name", "date",
        "utm_source", "utm_medium", "utm_campaign", "utm_term", "utm_content",
    }
    | {f"p{i}" for i in range(1, 11)}
)

_MACRO_PATTERN = re.compile(r"\{([a-z0-9_]+)\}")


def substitute_macros(template: str, values: dict[str, object]) -> tuple[str, list[str]]:
    """Returns (result, macros_used). Unknown macros are left literally in
    place and excluded from macros_used."""
    used: list[str] = []

    def _replace(match: re.Match) -> str:
        name = match.group(1)
        if name not in APPROVED_MACROS:
            return match.group(0)  # untouched — never evaluate the unknown
        used.append(name)
        value = values.get(name)
        text = "" if value is None else str(value)[:MAX_MACRO_VALUE_LENGTH]
        return quote(text, safe="")

    return _MACRO_PATTERN.sub(_replace, template), used


def macros_present(template: str) -> list[str]:
    return [m for m in _MACRO_PATTERN.findall(template or "")]


# ---------------------------------------------------------------------------
# Publisher-facing vocabulary (Part 17). This is the ONLY set a Publisher can
# use in their own postback URL. Internal platform mappings (Trackier/Trackix/
# Offer18 sub ids, UTM_*), advertiser revenue/original rate and margin are NOT
# part of it and are never resolved for a publisher postback.
# ---------------------------------------------------------------------------
PUBLISHER_MACROS: list[dict] = [
    {"token": "click_id", "label": "Click ID", "group": "Basic", "description": "Unique click identifier generated by Quantix. Use it to match conversions."},
    {"token": "campaign_id", "label": "Campaign ID", "group": "Basic", "description": "Quantix campaign ID."},
    {"token": "campaign_name", "label": "Campaign Name", "group": "Basic", "description": "Campaign title."},
    {"token": "publisher_id", "label": "Publisher ID", "group": "Basic", "description": "Your Publisher ID."},
    {"token": "event", "label": "Event / Goal", "group": "Basic", "description": "The event that converted (e.g. Install, Register, KYC, Trade)."},
    {"token": "status", "label": "Status", "group": "Basic", "description": "Conversion status."},
    {"token": "date", "label": "Date", "group": "Basic", "description": "Conversion date (YYYY-MM-DD, UTC)."},
    {"token": "date_time", "label": "Date & Time", "group": "Basic", "description": "Conversion date and time (ISO 8601, UTC)."},
    {"token": "ip", "label": "IP", "group": "Traffic / Geo", "description": "IP address recorded at click time."},
    {"token": "country", "label": "Country", "group": "Traffic / Geo", "description": "Country recorded at click time (blank if not captured)."},
    {"token": "country_code", "label": "Country Code", "group": "Traffic / Geo", "description": "Two-letter country code (blank if not captured)."},
    {"token": "state", "label": "State / Region", "group": "Traffic / Geo", "description": "State or region (blank if not captured)."},
    {"token": "city", "label": "City", "group": "Traffic / Geo", "description": "City (blank if not captured)."},
] + [
    {"token": f"p{i}", "label": f"P{i}", "group": "Publisher Parameters",
     "description": f"Custom parameter p{i} passed in your tracking link (blank if absent)."}
    for i in range(1, 11)
] + [
    {"token": "payout", "label": "Payout", "group": "Money", "description": "Your payout for this conversion."},
]

PUBLISHER_MACRO_KEYS: frozenset[str] = frozenset(m["token"] for m in PUBLISHER_MACROS)
