"""
Audit action names (spec §44). Plain string constants rather than a closed
Enum on purpose — the spec explicitly frames this list as a minimum, not an
exhaustive set, and later parts (campaigns, caps, payments, ...) will add
their own actions through the same audit_service without needing to touch
this file's enum every time.
"""

USER_REGISTERED = "USER_REGISTERED"
EMAIL_OTP_SENT = "EMAIL_OTP_SENT"
EMAIL_VERIFIED = "EMAIL_VERIFIED"
LOGIN_SUCCESS = "LOGIN_SUCCESS"
LOGIN_FAILED = "LOGIN_FAILED"
PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED"
PASSWORD_CHANGED = "PASSWORD_CHANGED"
INVITE_CREATED = "INVITE_CREATED"
INVITE_USED = "INVITE_USED"
INVITE_REVOKED = "INVITE_REVOKED"
INVITE_EXPIRED = "INVITE_EXPIRED"
MANAGER_APPROVAL_REQUESTED = "MANAGER_APPROVAL_REQUESTED"
MANAGER_APPROVED = "MANAGER_APPROVED"
MANAGER_REJECTED = "MANAGER_REJECTED"
PUBLISHER_APPROVAL_REQUESTED = "PUBLISHER_APPROVAL_REQUESTED"
PUBLISHER_APPROVED = "PUBLISHER_APPROVED"
PUBLISHER_REJECTED = "PUBLISHER_REJECTED"
PUBLISHER_APPLICATION_SUBMITTED = "PUBLISHER_APPLICATION_SUBMITTED"
PUBLISHER_MANAGER_ASSIGNED = "PUBLISHER_MANAGER_ASSIGNED"
PUBLISHER_MANAGER_REASSIGNED = "PUBLISHER_MANAGER_REASSIGNED"
WHATSAPP_GROUP_LINK_UPDATED = "WHATSAPP_GROUP_LINK_UPDATED"
GLOBAL_POSTBACK_SAVED = "GLOBAL_POSTBACK_SAVED"
GLOBAL_POSTBACK_DELETED = "GLOBAL_POSTBACK_DELETED"
EXPORT_JOB_REQUESTED = "EXPORT_JOB_REQUESTED"
MANAGER_MOBILE_UPDATED = "MANAGER_MOBILE_UPDATED"
ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED"
ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED"
LOGOUT = "LOGOUT"
REFRESH_REVOKED = "REFRESH_REVOKED"
REFRESH_DENIED_INACTIVE_USER = "REFRESH_DENIED_INACTIVE_USER"

# Part 3 (Super Admin panel)
CAMPAIGN_CREATED = "CAMPAIGN_CREATED"
CAMPAIGN_UPDATED = "CAMPAIGN_UPDATED"
CAMPAIGN_ACTIVATED = "CAMPAIGN_ACTIVATED"
CAMPAIGN_PAUSED = "CAMPAIGN_PAUSED"
CAMPAIGN_RESUMED = "CAMPAIGN_RESUMED"
CAMPAIGN_ENDED = "CAMPAIGN_ENDED"

# Part 4 foundation (campaign data purge + tracking-domain configuration)
CAMPAIGN_PURGED = "CAMPAIGN_PURGED"
TRACKING_DOMAIN_UPDATED = "TRACKING_DOMAIN_UPDATED"
ACCENT_THEME_UPDATED = "ACCENT_THEME_UPDATED"

# Part 5 (tracking engine)
TRACKING_LINK_CREATED = "TRACKING_LINK_CREATED"

# Part 6 (conversions + postbacks)
POSTBACK_ENDPOINT_CREATED = "POSTBACK_ENDPOINT_CREATED"
POSTBACK_ENDPOINT_DISABLED = "POSTBACK_ENDPOINT_DISABLED"
CONVERSION_CREATED = "CONVERSION_CREATED"
CONVERSION_STATUS_UPDATED = "CONVERSION_STATUS_UPDATED"
PUBLISHER_POSTBACK_CONFIG_SAVED = "PUBLISHER_POSTBACK_CONFIG_SAVED"
OUTBOUND_POSTBACK_REFIRED = "OUTBOUND_POSTBACK_REFIRED"

# Part 10 (integrations / API / webhooks)
API_KEY_CREATED = "API_KEY_CREATED"
API_KEY_REVOKED = "API_KEY_REVOKED"
WEBHOOK_CREATED = "WEBHOOK_CREATED"
WEBHOOK_TOGGLED = "WEBHOOK_TOGGLED"
WEBHOOK_REPLAYED = "WEBHOOK_REPLAYED"

# Part 3 (Fraud & Security foundation)
BLOCKED_IP_CREATED = "BLOCKED_IP_CREATED"
BLOCKED_IP_MARKED_SAFE = "BLOCKED_IP_MARKED_SAFE"
BLOCKED_IP_KEPT_BLOCKED = "BLOCKED_IP_KEPT_BLOCKED"
BLOCKED_IP_PERMANENT_BLOCK = "BLOCKED_IP_PERMANENT_BLOCK"
BLOCKED_IP_INVESTIGATION_TOGGLED = "BLOCKED_IP_INVESTIGATION_TOGGLED"

# Part 9 (Financials + Payments)
EARNING_CREATED = "EARNING_CREATED"
EARNING_REVERSED = "EARNING_REVERSED"
WITHDRAWAL_REQUESTED = "WITHDRAWAL_REQUESTED"
WITHDRAWAL_UNDER_REVIEW = "WITHDRAWAL_UNDER_REVIEW"
WITHDRAWAL_APPROVED = "WITHDRAWAL_APPROVED"
WITHDRAWAL_REJECTED = "WITHDRAWAL_REJECTED"
WITHDRAWAL_PAID = "WITHDRAWAL_PAID"
WITHDRAWAL_CANCELLED = "WITHDRAWAL_CANCELLED"
FINANCIAL_ADJUSTMENT_CREATED = "FINANCIAL_ADJUSTMENT_CREATED"
EARNING_CREATION_FAILED = "EARNING_CREATION_FAILED"

# Part 11 (Security / Operations / Support)
SUPPORT_TICKET_CREATED = "SUPPORT_TICKET_CREATED"
SUPPORT_TICKET_REPLIED = "SUPPORT_TICKET_REPLIED"
SUPPORT_TICKET_STATUS_CHANGED = "SUPPORT_TICKET_STATUS_CHANGED"
SESSION_REVOKED_BY_ADMIN = "SESSION_REVOKED_BY_ADMIN"
ALL_SESSIONS_REVOKED_BY_ADMIN = "ALL_SESSIONS_REVOKED_BY_ADMIN"

# Campaign access + company-report reconciliation
CAMPAIGN_ACCESS_REQUESTED = "CAMPAIGN_ACCESS_REQUESTED"
CAMPAIGN_ACCESS_APPROVED = "CAMPAIGN_ACCESS_APPROVED"
CAMPAIGN_ACCESS_REJECTED = "CAMPAIGN_ACCESS_REJECTED"
CONVERSION_REPORT_CONFIRMED = "CONVERSION_REPORT_CONFIRMED"
CONVERSION_REPORT_REJECTED = "CONVERSION_REPORT_REJECTED"
